### PR TITLE
Add scalafmt to the project

### PR DESCRIPTION
**Pull request by PatrykRudnicki**

### CODE REVIEW

**Comment by bambuchaAdm** [comment]
> Can you add a precheck script at the same time?

@SteveSugden what do you think about precheck sbt command instead of script ?

**Comment by PatrykRudnicki** [comment]
> Can you add a precheck script at the same time?

Yes, of course

**Comment by SteveSugden** [comment]
Not sure what that is.   Just suggesting we do what our other services do

**Comment by bambuchaAdm** [comment]
> Not sure what that is. Just suggesting we do what our other services do

@SteveSugden Main difference would be not `./precheck.sh` but `sbt precheck`

**Comment by PatrykRudnicki** [comment]
Sorry, last PR created headers in all files

**Comment by SteveSugden** [comment]
Headers are good!  Someone had to do it.

**Pull request merged**
